### ISSUE TITLE
This needs a homebrew formula.

### ISSUE THREAD

**Issue by jasonhemann** [xenodium/macosrec#1]

**Comment by xenodium** [comment]
Great idea. Do you happen to have some experience with it? Keen to contribute?

**Comment by xenodium** [comment]
I'm new at this, but looks like I may have a Homebrew formula. Could you please try it out?

```
brew tap xenodium/macosrec
brew install macosrec
```

**Comment by jasonhemann** [comment]
You're faster and quicker than I! It's not working yet for me, but I don't have a reason for you. Regardless, I think this will be so useful it'll become ubiquitous!

```
 brew tap xenodium/macrosrec
==> Tapping xenodium/macrosrec
Cloning into '/opt/homebrew/Library/Taps/xenodium/homebrew-macrosrec'...
brremote: Repository not found.
fatal: repository 'https://github.com/xenodium/homebrew-macrosrec/' not found
eError: Failure while executing; `git clone https://github.com/xenodium/homebrew-macrosrec /opt/homebrew/Library/Taps/xenodium/homebrew-macrosrec --origin=origin --template=` exited with 128.
w
```

**Comment by xenodium** [comment]
`brew tap xenodium/macrosrec`

There's a typo there. Should be:

`brew tap xenodium/macosrec`

See if you still have issues.

**Comment by jasonhemann** [comment]
Ack! Sorry! I'm doing better.

In fact well enough that this might be an issue on my system, rather than something on your end. I'm on an outdated version of macOS, and so my XCode is out of date (I get warnings about that prior to the output I show below). I suspect that I'll be without until I upgrade. /Probably/ working, and I'll let someone with an up-to-date OS confirm it for us.

```

==> swift build -c release --disable-sandbox
Last 15 lines from /Users/jhemann/Library/Logs/Homebrew/macosrec/01.swift:
2023-04-15 23:28:27 +0000

swift
build
-c
release
--disable-sandbox

warning: /Users/jhemann/Library/org.swift.swiftpm/configuration is not accessible or not writable, disabling user-level configuration features.
warning: /Users/jhemann/Library/org.swift.swiftpm/security is not accessible or not writable, disabling user-level security features.
warning: /Users/jhemann/Library/Caches/org.swift.swiftpm is not accessible or not writable, disabling user-level cache features.
error: 'macosrec-macosrec-0.1.0': package 'macosrec-macosrec-0.1.0' is using Swift tools version 5.8.0 but the installed version is 5.7.1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/homebrew-core):
  https://github.com/xenodium/homebrew-macosrec/issues
```

**Comment by xenodium** [comment]
Relaxed the swift pacakge version. Try

```
brew update
brew install macosrec
```

**Comment by jasonhemann** [comment]
Mission accomplished!!

**Comment by sebastienbarre** [comment]
Seems the requirements are still pretty high:
```
macosrec: A full installation of Xcode.app 14.0 is required to compile
this software. Installing just the Command Line Tools is not sufficient.

Xcode 14.0 cannot be installed on macOS 12.
You must upgrade your version of macOS.
```
I'm still on Monterey, and I suspect a fair amount of people are too, it's only from late 2021. 
Thanks

**Comment by xenodium** [comment]
> I'm still on Monterey

Can you clone repo, modify requirements in Package.swift, and build locally with `swift build`? If you can report back values confirming it builds and runs, I can update everything (including Homebrew formula).
