### ISSUE TITLE
Can the recorded videos preserve the window size correctly when the recorded window is resized?

### ISSUE THREAD

**Issue by Dima-369** [xenodium/macosrec#3]
I tested with Firefox and the final video always has the resolution of the last taken frame (I think). Can it be changed so it uses the largest window size and then centers the window in the video when the window is smaller? Because right now, it stretches the aspect ratio.

Right now, it plays really weird with the aspect ratio as well. In this video, I resized the Firefox window:

https://user-images.githubusercontent.com/15002298/233803565-c8473c1d-86ef-42ba-b9b0-39a60865d33a.mov

**Comment by xenodium** [comment]
Thanks for filing. May not have time to get to it very soon. Want to give it a go? It's probably here: https://github.com/xenodium/macosrec/blob/d74c6c075665977756d117b68beb2adb6b0b9fbf/Sources/main.swift#L534

Instead of taking the first frame find the biggest. Not super sure what effect it'll have on the outcome though.

Edit: typo

**Comment by Dima-369** [comment]
> Not super sure what effect it'll have on the outcome though.

Not a good one 😄 It keeps the outcome video at that resolution (I just tested with a hardcoded resolution) but then stretches the window to that resolution aspect ratio, so it looks just as weird as in my video from the issue description. It needs more work than that apparently.

**Comment by xenodium** [comment]
> I just tested with a hardcoded resolution

Thanks for testing it out.

I got curious to see what other tools did. For example, [Gifox](https://apps.apple.com/us/app/gifox-2/id1461845568?mt=12) had similar challenges.

> It needs more work than that apparently.

Ah, beyond the suggestion, I'm not too sure I'll have much time to figure out how to support this use-case. It's not something I need at the moment. Sorry :/ PRs totally welcome though.

Maybe the built-in tool `Command-Shift-5` via region is a better suited tool for this kind of scenario?

**Comment by Dima-369** [comment]
> Ah, beyond the suggestion, I'm not too sure I'll have much time to figure out how to support this use-case. It's not something I need at the moment. Sorry :/ PRs totally welcome though.
>
> Maybe the built-in tool Command-Shift-5 via region is a better suited tool for this kind of scenario?

Yeah, I suspected that this feature might be out of scope for this 'simpler' app. Command-Shift-5 definitely does the job in that instance. 

I actually just wanted to report this because I didn't find anything about it in the README and was wondering if this is even supported.

**Comment by xenodium** [comment]
> I actually just wanted to report this because I didn't find anything about it in the README and was wondering if this is even supported.

Ah, good point. I'll update the README to make this more explicit.
