### ISSUE TITLE
When running in a full screen Terminal window, it only lists apps that have  an entry in the menubar

### ISSUE THREAD

**Issue by gotofritz** [xenodium/macosrec#5]
Hi, thanks for the great util.

I am running it from a full screen Terminal window. I have a few apps open, including Chrome and Firefox, but it can't find most of them.
However, it lists all of these, which appear in the menubar (the Control Centres seem to be things like the wireless icon, the battery icon, end so on):

```
322044 Control Centre
322043 Control Centre
322042 Control Centre
322041 Control Centre
322038 Control Centre
322864 Dock - Fullscreen Backdrop
322865 Dock - Desktop Picture - DefaultDesktop.heic
322052 Dock - Desktop Picture - DefaultDesktop.heic
322034 SystemUIServer
322040 SystemUIServer
322049 TextInputMenuAgent
322045 Rocket
322047 Flux
```

If I come out of Full Screen it shows me all of the above + a  of running apps which are not in full screen.
It seems that each Full Screen window is its own little universe

Running Ventura 13.4 (22F66)

**Comment by xenodium** [comment]
Added `--hidden` to be used with `--list` it in  77a4ebd. Note that not all hidden windows are up for grabs.

**Comment by xenodium** [comment]
Homebrew should point to the latest, in case you're using that. Lemme know how you get on.

**Comment by gotofritz** [comment]
Hi, thanks for the amend. It does list a lot more windows, but when it comes to recording / screenshotting them it still can't find them. But don't worry, no biggie, I'll just run from a non-full screen window.
